-- =====================================================================
-- E-Commerce Order Management Database System
-- Week 9: Database Creation using DDL (Oracle SQL / PL/SQL compatible)
-- =====================================================================
-- Oracle has no CREATE DATABASE for normal student use; the "database"
-- is a schema (user). Run the block below as SYS/SYSTEM (optional).
-- For Oracle XE 18c+/21c, use the pluggable DB: ALTER SESSION SET CONTAINER = XEPDB1;
--
-- CREATE USER ecommerce IDENTIFIED BY ecommerce123;
-- GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO ecommerce;
-- ALTER USER ecommerce QUOTA UNLIMITED ON USERS;
-- CONNECT ecommerce/ecommerce123
-- =====================================================================

-- ---------------------------------------------------------------------
-- Optional clean-up (child tables first). Uncomment to re-run the script.
-- ---------------------------------------------------------------------
-- DROP TABLE Review CASCADE CONSTRAINTS;
-- DROP TABLE Shipment CASCADE CONSTRAINTS;
-- DROP TABLE Payment CASCADE CONSTRAINTS;
-- DROP TABLE Order_Details CASCADE CONSTRAINTS;
-- DROP TABLE Orders CASCADE CONSTRAINTS;
-- DROP TABLE Product CASCADE CONSTRAINTS;
-- DROP TABLE Supplier CASCADE CONSTRAINTS;
-- DROP TABLE Category CASCADE CONSTRAINTS;
-- DROP TABLE Customer CASCADE CONSTRAINTS;

-- ---------------------------------------------------------------------
-- 1. CUSTOMER
-- ---------------------------------------------------------------------
CREATE TABLE Customer (
    customer_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name      VARCHAR2(100) NOT NULL,
    email              VARCHAR2(100) NOT NULL,
    mobile_number      VARCHAR2(15)  NOT NULL,
    address            VARCHAR2(255),
    registration_date  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_customer        PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_email  UNIQUE (email),
    CONSTRAINT uq_customer_mobile UNIQUE (mobile_number),
    CONSTRAINT ck_customer_email  CHECK (email LIKE '%_@_%._%'),
    CONSTRAINT ck_customer_mobile CHECK (REGEXP_LIKE(mobile_number, '^[0-9+]{10,15}$'))
);

-- ---------------------------------------------------------------------
-- 2. CATEGORY
-- ---------------------------------------------------------------------
CREATE TABLE Category (
    category_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name  VARCHAR2(100) NOT NULL,
    description    VARCHAR2(500),
    CONSTRAINT pk_category      PRIMARY KEY (category_id),
    CONSTRAINT uq_category_name UNIQUE (category_name)
);

-- ---------------------------------------------------------------------
-- 3. SUPPLIER
-- ---------------------------------------------------------------------
CREATE TABLE Supplier (
    supplier_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_name   VARCHAR2(100) NOT NULL,
    contact_email   VARCHAR2(100),
    contact_phone   VARCHAR2(15),
    CONSTRAINT pk_supplier       PRIMARY KEY (supplier_id),
    CONSTRAINT uq_supplier_name  UNIQUE (supplier_name),
    CONSTRAINT uq_supplier_email UNIQUE (contact_email)
);

-- ---------------------------------------------------------------------
-- 4. PRODUCT  (belongs to one Category, supplied by one Supplier)
-- ---------------------------------------------------------------------
CREATE TABLE Product (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_name    VARCHAR2(150) NOT NULL,
    price           NUMBER(10,2)  NOT NULL,
    stock_quantity  NUMBER(8)     DEFAULT 0 NOT NULL,
    category_id     NUMBER        NOT NULL,
    supplier_id     NUMBER,
    CONSTRAINT pk_product          PRIMARY KEY (product_id),
    CONSTRAINT ck_product_price    CHECK (price > 0),
    CONSTRAINT ck_product_stock    CHECK (stock_quantity >= 0),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES Category(category_id),
    CONSTRAINT fk_product_supplier FOREIGN KEY (supplier_id) REFERENCES Supplier(supplier_id)
);

-- ---------------------------------------------------------------------
-- 5. ORDERS  (named Orders because ORDER is a reserved word)
-- ---------------------------------------------------------------------
CREATE TABLE Orders (
    order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id   NUMBER        NOT NULL,
    order_date    DATE          DEFAULT SYSDATE NOT NULL,
    total_amount  NUMBER(12,2)  DEFAULT 0 NOT NULL,
    order_status  VARCHAR2(20)  DEFAULT 'PLACED' NOT NULL,
    CONSTRAINT pk_orders          PRIMARY KEY (order_id),
    CONSTRAINT ck_orders_total    CHECK (total_amount >= 0),
    CONSTRAINT ck_orders_status   CHECK (order_status IN
                                  ('PLACED','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id)
);

-- ---------------------------------------------------------------------
-- 6. ORDER_DETAILS  (resolves Orders <-> Product many-to-many)
-- ---------------------------------------------------------------------
CREATE TABLE Order_Details (
    order_detail_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id         NUMBER       NOT NULL,
    product_id       NUMBER       NOT NULL,
    quantity         NUMBER(6)    NOT NULL,
    unit_price       NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_order_details     PRIMARY KEY (order_detail_id),
    CONSTRAINT uq_order_product     UNIQUE (order_id, product_id),
    CONSTRAINT ck_od_quantity       CHECK (quantity > 0),
    CONSTRAINT ck_od_unit_price     CHECK (unit_price > 0),
    CONSTRAINT fk_od_order          FOREIGN KEY (order_id)   REFERENCES Orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_od_product        FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

-- ---------------------------------------------------------------------
-- 7. PAYMENT
-- ---------------------------------------------------------------------
CREATE TABLE Payment (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id        NUMBER        NOT NULL,
    payment_method  VARCHAR2(20)  NOT NULL,
    payment_date    DATE          DEFAULT SYSDATE NOT NULL,
    payment_status  VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT pk_payment        PRIMARY KEY (payment_id),
    CONSTRAINT ck_payment_method CHECK (payment_method IN
                                 ('CREDIT_CARD','DEBIT_CARD','UPI','NET_BANKING','COD','WALLET')),
    CONSTRAINT ck_payment_status CHECK (payment_status IN
                                 ('PENDING','SUCCESS','FAILED','REFUNDED')),
    CONSTRAINT fk_payment_order  FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);

-- ---------------------------------------------------------------------
-- 8. SHIPMENT
-- ---------------------------------------------------------------------
CREATE TABLE Shipment (
    shipment_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id          NUMBER        NOT NULL,
    delivery_address  VARCHAR2(255) NOT NULL,
    shipment_date     DATE,
    delivery_status   VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT pk_shipment        PRIMARY KEY (shipment_id),
    CONSTRAINT uq_shipment_order  UNIQUE (order_id),
    CONSTRAINT ck_shipment_status CHECK (delivery_status IN
                                  ('PENDING','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','RETURNED')),
    CONSTRAINT fk_shipment_order  FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);

-- ---------------------------------------------------------------------
-- 9. REVIEW
-- ---------------------------------------------------------------------
CREATE TABLE Review (
    review_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id   NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    rating        NUMBER(1) NOT NULL,
    comments      VARCHAR2(1000),
    review_date   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_review          PRIMARY KEY (review_id),
    CONSTRAINT uq_review_cust_prod UNIQUE (customer_id, product_id),
    CONSTRAINT ck_review_rating   CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_review_customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id),
    CONSTRAINT fk_review_product  FOREIGN KEY (product_id)  REFERENCES Product(product_id)
);

-- ---------------------------------------------------------------------
-- Indexes on foreign keys (speeds up joins and reports)
-- ---------------------------------------------------------------------
CREATE INDEX idx_product_category ON Product(category_id);
CREATE INDEX idx_product_supplier ON Product(supplier_id);
CREATE INDEX idx_orders_customer  ON Orders(customer_id);
CREATE INDEX idx_orders_date      ON Orders(order_date);
CREATE INDEX idx_od_product       ON Order_Details(product_id);
CREATE INDEX idx_payment_order    ON Payment(order_id);
CREATE INDEX idx_review_product   ON Review(product_id);

-- ---------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------
SELECT table_name FROM user_tables ORDER BY table_name;

SELECT table_name, constraint_name, constraint_type
FROM   user_constraints
WHERE  constraint_type IN ('P','R','U','C')
AND    table_name IN ('CUSTOMER','CATEGORY','SUPPLIER','PRODUCT','ORDERS',
                      'ORDER_DETAILS','PAYMENT','SHIPMENT','REVIEW')
AND    constraint_name NOT LIKE 'SYS_C%'
ORDER BY table_name, constraint_type;

DESC Customer;
DESC Product;
DESC Orders;
